-- CREATE TABLE THINGS;
CREATE TABLE THINGS(
	  THINGID VARCHAR(10) NOT NULL,
	  THINGNAME VARCHAR(100) NOT NULL
);

ALTER TABLE THINGS ADD CONSTRAINT PK_MEMBER PRIMARY KEY (THINGID);

INSERT INTO THINGS (THINGNAME, THINGID) VALUES ('House', '1234');
INSERT INTO THINGS (THINGNAME, THINGID) VALUES ('TV', '2222');
INSERT INTO THINGS (THINGNAME, THINGID) VALUES ('Table', '3333');
